import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, Show, SignInButton, UserButton } from '@clerk/nextjs';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <ClerkProvider>
          <header style={{ display: 'flex', justifyContent: 'flex-end', padding: '1rem', gap: '1rem' }}>
  <Show when="signed-out">
    <SignInButton />
  </Show>
  <Show when="signed-in">
    <UserButton />
  </Show>
</header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}